// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"unit21/pkg/models/shared"
)

type AddInstrumentsRequest struct {
	EntityID       string                 `pathParam:"style=simple,explode=false,name=entity_id"`
	LinkInstrument *shared.LinkInstrument `request:"mediaType=application/json"`
	// Name of organization in your environment
	OrgName string `pathParam:"style=simple,explode=false,name=org_name"`
}

type AddInstrumentsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// NOT FOUND
	ErrorResponse *shared.ErrorResponse
}
