// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"unit21/pkg/models/shared"
)

// CreateInstrumentMessageGeneralResponse - OK
type CreateInstrumentMessageGeneralResponse struct {
	// Error message
	ErrorCode *string `json:"error_code,omitempty"`
	// Detailed message
	Message *string `json:"message,omitempty"`
}

type CreateInstrumentResponse struct {
	ContentType string
	// OK
	MessageGeneralResponse *CreateInstrumentMessageGeneralResponse
	StatusCode             int
	RawResponse            *http.Response
	// OK
	CreateInstrumentResponse *shared.CreateInstrumentResponse
}
