// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// CreateVerificationFormRequestBody - Set session length. Not required.
type CreateVerificationFormRequestBody struct {
	// Time in minutes that form will be valid. Once this expires, the user can no longer submit or view the form. Max is 10080 minutes (one week). Default is 1440 minutes (one day)
	//
	SessionLengthMinutes *int64 `json:"session_length_minutes,omitempty"`
}

// CreateVerificationForm200ApplicationJSON - OK
type CreateVerificationForm200ApplicationJSON struct {
	// URL to redirect users to fill out form
	RedirectTo *string `json:"redirect_to,omitempty"`
}

type CreateVerificationFormResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	CreateVerificationForm200ApplicationJSONObject *CreateVerificationForm200ApplicationJSON
}
