// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DownloadFileExportRequest struct {
	// A Unit21 internally-assigned unique identifier for an a file.
	FileExportID int64 `pathParam:"style=simple,explode=false,name=file_export_id"`
}

type DownloadFileExportResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
