// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

// ExportSarsRequestBodyFiltersReportTypeEnum - Type of report.
type ExportSarsRequestBodyFiltersReportTypeEnum string

const (
	ExportSarsRequestBodyFiltersReportTypeEnumFincenSar   ExportSarsRequestBodyFiltersReportTypeEnum = "FINCEN_SAR"
	ExportSarsRequestBodyFiltersReportTypeEnumEstonianFiu ExportSarsRequestBodyFiltersReportTypeEnum = "ESTONIAN_FIU"
	ExportSarsRequestBodyFiltersReportTypeEnumGoamlStr    ExportSarsRequestBodyFiltersReportTypeEnum = "GOAML_STR"
	ExportSarsRequestBodyFiltersReportTypeEnumNcaSar      ExportSarsRequestBodyFiltersReportTypeEnum = "NCA_SAR"
)

func (e ExportSarsRequestBodyFiltersReportTypeEnum) ToPointer() *ExportSarsRequestBodyFiltersReportTypeEnum {
	return &e
}

func (e *ExportSarsRequestBodyFiltersReportTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "FINCEN_SAR":
		fallthrough
	case "ESTONIAN_FIU":
		fallthrough
	case "GOAML_STR":
		fallthrough
	case "NCA_SAR":
		*e = ExportSarsRequestBodyFiltersReportTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ExportSarsRequestBodyFiltersReportTypeEnum: %s", s)
	}
}

type ExportSarsRequestBodyFiltersStatusesEnum string

const (
	ExportSarsRequestBodyFiltersStatusesEnumArchived                     ExportSarsRequestBodyFiltersStatusesEnum = "ARCHIVED"
	ExportSarsRequestBodyFiltersStatusesEnumPrefilingValidationPending   ExportSarsRequestBodyFiltersStatusesEnum = "PREFILING_VALIDATION_PENDING"
	ExportSarsRequestBodyFiltersStatusesEnumPrefilingValidationInProcess ExportSarsRequestBodyFiltersStatusesEnum = "PREFILING_VALIDATION_IN_PROCESS"
	ExportSarsRequestBodyFiltersStatusesEnumPrefilingValidationFailed    ExportSarsRequestBodyFiltersStatusesEnum = "PREFILING_VALIDATION_FAILED"
	ExportSarsRequestBodyFiltersStatusesEnumPrefilingValidationSuccess   ExportSarsRequestBodyFiltersStatusesEnum = "PREFILING_VALIDATION_SUCCESS"
	ExportSarsRequestBodyFiltersStatusesEnumQueuedForFiling              ExportSarsRequestBodyFiltersStatusesEnum = "QUEUED_FOR_FILING"
	ExportSarsRequestBodyFiltersStatusesEnumReadyForReview               ExportSarsRequestBodyFiltersStatusesEnum = "READY_FOR_REVIEW"
	ExportSarsRequestBodyFiltersStatusesEnumSendingToFincen              ExportSarsRequestBodyFiltersStatusesEnum = "SENDING_TO_FINCEN"
	ExportSarsRequestBodyFiltersStatusesEnumSentToFincen                 ExportSarsRequestBodyFiltersStatusesEnum = "SENT_TO_FINCEN"
	ExportSarsRequestBodyFiltersStatusesEnumFilingFailed                 ExportSarsRequestBodyFiltersStatusesEnum = "FILING_FAILED"
	ExportSarsRequestBodyFiltersStatusesEnumFilingMaxRetriesExceeded     ExportSarsRequestBodyFiltersStatusesEnum = "FILING_MAX_RETRIES_EXCEEDED"
	ExportSarsRequestBodyFiltersStatusesEnumFilingSuccess                ExportSarsRequestBodyFiltersStatusesEnum = "FILING_SUCCESS"
	ExportSarsRequestBodyFiltersStatusesEnumFincenValidationFailed       ExportSarsRequestBodyFiltersStatusesEnum = "FINCEN_VALIDATION_FAILED"
	ExportSarsRequestBodyFiltersStatusesEnumFincenRejected               ExportSarsRequestBodyFiltersStatusesEnum = "FINCEN_REJECTED"
	ExportSarsRequestBodyFiltersStatusesEnumFincenStatusOther            ExportSarsRequestBodyFiltersStatusesEnum = "FINCEN_STATUS_OTHER"
	ExportSarsRequestBodyFiltersStatusesEnumFincenAccepted               ExportSarsRequestBodyFiltersStatusesEnum = "FINCEN_ACCEPTED"
)

func (e ExportSarsRequestBodyFiltersStatusesEnum) ToPointer() *ExportSarsRequestBodyFiltersStatusesEnum {
	return &e
}

func (e *ExportSarsRequestBodyFiltersStatusesEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "ARCHIVED":
		fallthrough
	case "PREFILING_VALIDATION_PENDING":
		fallthrough
	case "PREFILING_VALIDATION_IN_PROCESS":
		fallthrough
	case "PREFILING_VALIDATION_FAILED":
		fallthrough
	case "PREFILING_VALIDATION_SUCCESS":
		fallthrough
	case "QUEUED_FOR_FILING":
		fallthrough
	case "READY_FOR_REVIEW":
		fallthrough
	case "SENDING_TO_FINCEN":
		fallthrough
	case "SENT_TO_FINCEN":
		fallthrough
	case "FILING_FAILED":
		fallthrough
	case "FILING_MAX_RETRIES_EXCEEDED":
		fallthrough
	case "FILING_SUCCESS":
		fallthrough
	case "FINCEN_VALIDATION_FAILED":
		fallthrough
	case "FINCEN_REJECTED":
		fallthrough
	case "FINCEN_STATUS_OTHER":
		fallthrough
	case "FINCEN_ACCEPTED":
		*e = ExportSarsRequestBodyFiltersStatusesEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ExportSarsRequestBodyFiltersStatusesEnum: %s", s)
	}
}

// ExportSarsRequestBodyFilters - Filter to narrow down sars in export
type ExportSarsRequestBodyFilters struct {
	// Report Creation end date.
	CreatedAtEnd *string `json:"created_at_end,omitempty"`
	// Report creation start date.
	CreatedAtStart *string `json:"created_at_start,omitempty"`
	// Report file end date.
	FiledAtEnd *string `json:"filed_at_end,omitempty"`
	// Report file start date.
	FiledAtStart *string `json:"filed_at_start,omitempty"`
	// Type of report.
	ReportType *ExportSarsRequestBodyFiltersReportTypeEnum `json:"report_type,omitempty"`
	// Status of the sar.
	Status *string `json:"status,omitempty"`
	// Status for the sars.
	Statuses []ExportSarsRequestBodyFiltersStatusesEnum `json:"statuses,omitempty"`
	// Report submited?
	Submitted *bool `json:"submitted,omitempty"`
	// Numerical IDs of the tags.
	TagIds []int64 `json:"tag_ids,omitempty"`
	// Report update end date.
	UpdatedAtEnd *string `json:"updated_at_end,omitempty"`
	// Report update start date.
	UpdatedAtStart *string `json:"updated_at_start,omitempty"`
}

type ExportSarsRequestBody struct {
	// Filter to narrow down sars in export
	Filters *ExportSarsRequestBodyFilters `json:"filters,omitempty"`
	// Array of the unique identifiers of the sar IDs.
	SarIds []int64 `json:"sar_ids,omitempty"`
}

type ExportSarsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
