// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"unit21/pkg/models/shared"
)

type GetEntityRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entity_id"`
	// Name of organization in your environment
	OrgName string `pathParam:"style=simple,explode=false,name=org_name"`
}

// GetEntityMessageGeneralResponse - OK
type GetEntityMessageGeneralResponse struct {
	// Error message
	ErrorCode *string `json:"error_code,omitempty"`
	// Detailed message
	Message *string `json:"message,omitempty"`
}

type GetEntityResponse struct {
	ContentType string
	// OK
	MessageGeneralResponse *GetEntityMessageGeneralResponse
	StatusCode             int
	RawResponse            *http.Response
	// OK
	EntityList *shared.EntityList
}
