// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetPreSignedURLRequestBody struct {
	// File name.
	FileName string `json:"file_name"`
	// Unique hash. Requires UUID format. Used if filename is not unique.
	Md5Hash *string `json:"md5_hash,omitempty"`
	// Stream name.
	StreamName string `json:"stream_name"`
}

type GetPreSignedURLResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
