// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"unit21/pkg/models/shared"
)

type ListDevicesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ListResponse *shared.ListResponse
}
