// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListDatafilesRequestBody struct {
	// Unix timestamp for the time range at which the pre-signed-url was requested.
	CreatedAfter *int64 `json:"created_after,omitempty"`
	// Unix timestamp for the time range at which the pre-signed-url was requested.
	CreatedBefore *int64 `json:"created_before,omitempty"`
}

type ListDatafilesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
