// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListSarsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
