// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"unit21/pkg/models/shared"
)

// ListInstrumentsMessageGeneralResponse - OK
type ListInstrumentsMessageGeneralResponse struct {
	// Error message
	ErrorCode *string `json:"error_code,omitempty"`
	// Detailed message
	Message *string `json:"message,omitempty"`
}

type ListInstrumentsResponse struct {
	ContentType string
	// OK
	MessageGeneralResponse *ListInstrumentsMessageGeneralResponse
	StatusCode             int
	RawResponse            *http.Response
	// OK
	ListInstrumentResponse *shared.ListInstrumentResponse
}
