// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"unit21/pkg/models/shared"
)

type UpdateEntityRequest struct {
	// Any or all of the following objects are accepted
	RequestBody interface{} `request:"mediaType=application/json"`
	EntityID    string      `pathParam:"style=simple,explode=false,name=entity_id"`
	// Name of organization in your environment
	OrgName string `pathParam:"style=simple,explode=false,name=org_name"`
}

// UpdateEntityMessageGeneralResponse - OK
type UpdateEntityMessageGeneralResponse struct {
	// Error message
	ErrorCode *string `json:"error_code,omitempty"`
	// Detailed message
	Message *string `json:"message,omitempty"`
}

type UpdateEntityResponse struct {
	ContentType string
	// OK
	MessageGeneralResponse *UpdateEntityMessageGeneralResponse
	StatusCode             int
	RawResponse            *http.Response
	// OK
	UpdateEntityResponse *shared.UpdateEntityResponse
}
