// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UploadDatafilesRequestBodyFile struct {
	Content []byte `multipartForm:"content"`
	File    string `multipartForm:"name=file"`
}

type UploadDatafilesRequestBody struct {
	File *UploadDatafilesRequestBodyFile `multipartForm:"file"`
}

type UploadDatafilesRequest struct {
	RequestBody *UploadDatafilesRequestBody `request:"mediaType=multipart/form-data"`
	// A Unit21 internally-assigned unique url for an AWS S3 bucket where your organization can upload data.
	PreSignedURL string `pathParam:"style=simple,explode=false,name=pre_signed_url"`
}

type UploadDatafilesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
