// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AlertsAlertType - Either transaction monitoring, `tm`, or know-your-customer `kyc`. Default is `tm`
type AlertsAlertType string

const (
	AlertsAlertTypeTm          AlertsAlertType = "tm"
	AlertsAlertTypeKyc         AlertsAlertType = "kyc"
	AlertsAlertTypeChainalysis AlertsAlertType = "chainalysis"
)

func (e AlertsAlertType) ToPointer() *AlertsAlertType {
	return &e
}

func (e *AlertsAlertType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tm":
		fallthrough
	case "kyc":
		fallthrough
	case "chainalysis":
		*e = AlertsAlertType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AlertsAlertType: %v", v)
	}
}

type Alerts struct {
	// Unique identifier of the alert on the customer's platform.
	AlertID string `json:"alert_id"`
	// Either transaction monitoring, `tm`, or know-your-customer `kyc`. Default is `tm`
	AlertType AlertsAlertType `json:"alert_type"`
	// Date in seconds since 1 Jan 1970 00:00:00 UTC (i.e. in [Unix time](https://en.wikipedia.org/wiki/Unix_time)).
	CreatedAt int64 `json:"created_at"`
	// Description of the alert
	Description *string `json:"description,omitempty"`
	// Labels that describe the outcome of an alert or case investigation. More info in [this knowledge base article about dispositions](https://docs.unit21.ai/docs/concept-dispositions).
	Disposition *string `json:"disposition,omitempty"`
	// Free form text documenting reasoning and investigation notes
	DispositionNotes *string `json:"disposition_notes,omitempty"`
	// Investigation status, either `OPEN` or `ClOSED`
	Status InvestigationStatus `json:"status"`
	// List of string tags, in the format `keyString:valueString` (note that the Key strings are NOT enclosed in `"`)
	Tags []string `json:"tags,omitempty"`
	// Title of the alert
	Title string `json:"title"`
	// Integer value greater than or equal to 1. Used when `alert_type` is `kyc`.
	VerificationResultID *int64 `json:"verification_result_id,omitempty"`
}
