// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BlacklistBusiness struct {
	// The registered name of the business
	BusinessName *string `json:"business_name,omitempty"`
	// Associated city (max 128 characters)
	City *string `json:"city,omitempty"`
	// The TIN/EIN of the business
	CorporateTaxID *string `json:"corporate_tax_id,omitempty"`
	// Country of primary residence such as "USA", "United States", "US", "The United States of America"
	Country *string `json:"country,omitempty"`
	// Operating name of the business.
	DbaName *string `json:"dba_name,omitempty"`
	// Any string representing a state such as "CA" or "California"
	State *string `json:"state,omitempty"`
	// Street name and address number
	Street *string `json:"street,omitempty"`
	// Associated ZIP code or postal code. For US addresses, can be either 5-digit ZIP Code (99999) or ZIP+4 Code (99999-9999) formats
	ZipCode *string `json:"zip_code,omitempty"`
}
