// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BlacklistUser struct {
	// Alias or alternate first name
	AliasFirstName *string `json:"alias_first_name,omitempty"`
	// Alias or alternate middle name
	AliasMiddleName *string `json:"alias_middle_name,omitempty"`
	// Associated city (max 128 characters)
	City *string `json:"city,omitempty"`
	// Digital fingerprints(browser, os, device) associated with the entity.
	ClientFingerprint *string `json:"client_fingerprint,omitempty"`
	// Country of primary residence such as "USA", "United States", "US", "The United States of America"
	Country *string `json:"country,omitempty"`
	// In format MM/DD/YYYY
	DateOfBirth *string `json:"date_of_birth,omitempty"`
	// Email associated with this user
	Email *string `json:"email,omitempty"`
	// Status of the object on your system. You MAY enter any string value.
	EntityStatus *string `json:"entity_status,omitempty"`
	// Extra information how your organization classifies the entity. You MAY enter any value.
	//
	EntitySubtype *string `json:"entity_subtype,omitempty"`
	// User's associated first name
	FirstName *string `json:"first_name,omitempty"`
	// Either IPv4 or IPv6
	IPAddress *string `json:"ip_address,omitempty"`
	// User's associated last name
	LastName *string `json:"last_name,omitempty"`
	// User's associated middle name
	MiddleName *string `json:"middle_name,omitempty"`
	// List of phone numbers associated with the entity in [E.164 format](https://en.wikipedia.org/wiki/E.164)─e.g. +12125551395 ( '[+][country code][area code][local phone number]' )
	PhoneNumber *string `json:"phone_number,omitempty"`
	// Social security number of the user, in the format xxx-xx-xxxx
	Ssn *string `json:"ssn,omitempty"`
	// Any string representing a state such as "CA" or "California"
	State *string `json:"state,omitempty"`
	// Street name and address number
	Street *string `json:"street,omitempty"`
	// Associated ZIP code or postal code. For US addresses, can be either 5-digit ZIP Code (99999) or ZIP+4 Code (99999-9999) formats
	ZipCode *string `json:"zip_code,omitempty"`
}
