// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BlacklistString struct {
	// string value to upload to blacklist
	BlacklistValue *string `json:"blacklist_value,omitempty"`
}
