// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BusinessData - Business data - business name, TIN/EIN etc.
type BusinessData struct {
	// Business data - business name, TIN/EIN etc. None of the fields in business_data are required. You may send in an empty array: `"business_data": {}`.
	//
	BusinessData *BusinessDataProperties `json:"business_data,omitempty"`
}
