// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CommunicationData struct {
	// An entity's associated means of communication, like emails and phone numbers.
	CommunicationData *CommunicationDataProperties `json:"communication_data,omitempty"`
}
