// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContinuousMonitoring struct {
	// Enable or disable continuous monitoring. Use `true` to turn on and `false` to turn off.
	//
	ContinuousMonitoring bool `json:"continuous_monitoring"`
	// Default: `false`. If `true`,  the response is returned in the request but may take slightly longer to complete.
	SynchronousResponse *bool `json:"synchronous_response,omitempty"`
}
