// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateAlertResponse - OK
type CreateAlertResponse struct {
	// Unique identifier of the alert on the customer's platform.
	AlertID *string `json:"alert_id,omitempty"`
	// During upserts, `true` when object already existed at the ID field specified in the POST.
	PreviouslyExisted *bool `json:"previously_existed,omitempty"`
	// A Unit21 internally-assigned unique identifier for an object within the Unit21 system.
	Unit21ID *string `json:"unit21_id,omitempty"`
}
