// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateEntityRequest struct {
	// Business data - business name, TIN/EIN etc. None of the fields in business_data are required. You may send in an empty array: `"business_data": {}`.
	//
	BusinessData *BusinessDataProperties `json:"business_data,omitempty"`
	// An entity's associated means of communication, like emails and phone numbers.
	CommunicationData *CommunicationDataProperties `json:"communication_data,omitempty"`
	// Any custom information that you wish our system to associate with this object  (accepts any valid JSON object -- up to 3 layers deep -- in key:value format --  `string:string`, `string:int`, `string:bool` -- no arrays)
	CustomData map[string]interface{} `json:"custom_data,omitempty"`
	// Associated digital properties - IP, device, browser, client info etc.
	DigitalData *DigitalDataArrayProperties `json:"digital_data,omitempty"`
	// Array of document data objects.
	DocumentData []DocumentDataProperties `json:"document_data,omitempty"`
	// General information about the entity. With this object, you can link any entity on Unit21's system to a user or business on your platform.
	GeneralData GeneralEntitiesProperties `json:"general_data"`
	// List of instrument_ids.
	InstrumentIds []string `json:"instrument_ids,omitempty"`
	// Array of location data objects.
	LocationData []LocationDataProperties `json:"location_data,omitempty"`
	// Options for specifying workflows and list merge strategies.
	Options *EntityOptionsProperties `json:"options,omitempty"`
	// An entity's associated intruments and entities (also called relationships)
	Relationships *RelationshipsDataProperties `json:"relationships,omitempty"`
	// Set of risk scores.
	RiskScores []RiskScoresProperties `json:"risk_scores,omitempty"`
	// Personal data - name, birthday, SSN etc. None of the fields in user_data are required. You may send in an empty array: `"user_data": {}`.
	//
	UserData *UserDataProperties `json:"user_data,omitempty"`
}
