// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CreateBlacklistType - A value indicating what type of fields the blacklist will contain. One of `STRING`, `IP_INET`, `IP_CIDR`, `USER`, or `BUSINESS`.
type CreateBlacklistType string

const (
	CreateBlacklistTypeString   CreateBlacklistType = "STRING"
	CreateBlacklistTypeIPInet   CreateBlacklistType = "IP_INET"
	CreateBlacklistTypeIPCidr   CreateBlacklistType = "IP_CIDR"
	CreateBlacklistTypeUser     CreateBlacklistType = "USER"
	CreateBlacklistTypeBusiness CreateBlacklistType = "BUSINESS"
)

func (e CreateBlacklistType) ToPointer() *CreateBlacklistType {
	return &e
}

func (e *CreateBlacklistType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "STRING":
		fallthrough
	case "IP_INET":
		fallthrough
	case "IP_CIDR":
		fallthrough
	case "USER":
		fallthrough
	case "BUSINESS":
		*e = CreateBlacklistType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateBlacklistType: %v", v)
	}
}

type CreateBlacklist struct {
	// A descriptive text field for the blacklist, maximum 512 characters in length.
	Description *string `json:"description,omitempty"`
	// A human-readable name for the blacklist.
	Name *string `json:"name,omitempty"`
	// A value indicating what type of fields the blacklist will contain. One of `STRING`, `IP_INET`, `IP_CIDR`, `USER`, or `BUSINESS`.
	Type *CreateBlacklistType `json:"type,omitempty"`
}
