// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DigitalDataArray struct {
	// Associated digital properties - IP, device, browser, client info etc.
	DigitalData *DigitalDataArrayProperties `json:"digital_data,omitempty"`
}
