// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DocumentDataArray struct {
	// Array of document data objects.
	DocumentData []DocumentDataProperties `json:"document_data,omitempty"`
}
