// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EntityVerification - Fields to verify an entity
type EntityVerification struct {
	// Include the full, raw, verification results. Can be used only if `synchronous_response` is `true`. Default is `false`.
	IncludeFullResponse *bool `json:"include_full_response,omitempty"`
	// **Default**: `false`. If `true`,  the APU immediately executes the workflow, and sends the verification result with the API response. If `true` and the workflow doesn't allow synchronous responses, the API returns an error.
	// **Note**: Using synchronous calls may cause the API to return a `423` error. If that happens, try switching `synchronous_response` to `false`.
	SynchronousResponse *bool `json:"synchronous_response,omitempty"`
	// A unique identifier defined during workflow creation. **Default**: none
	//
	WorkflowID string `json:"workflow_id"`
}
