// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EntityRelationsEntities struct {
	// Unique identifier of the entity. Entity IDs must be unique and only comprise of the characters -_:.@a-zA-Z0-9!#$%&*+/=?^`{'
	EntityID string `json:"entity_id"`
	// Describes a user such as `employee` or `business`
	EntityType *string `json:"entity_type,omitempty"`
	// Description of the relationship.
	RelationshipID *string `json:"relationship_id,omitempty"`
}

type EntityRelations struct {
	// List of entity relationships.
	Entities []EntityRelationsEntities `json:"entities,omitempty"`
}
