// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// EventType - `transaction` for monetary flows, `action` for other state changes, like new logins.
type EventType string

const (
	EventTypeTransaction EventType = "transaction"
	EventTypeAction      EventType = "action"
)

func (e EventType) ToPointer() *EventType {
	return &e
}

func (e *EventType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "transaction":
		fallthrough
	case "action":
		*e = EventType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EventType: %v", v)
	}
}
