// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type InstrumentArray struct {
	// Array of `instrument_id` strings
	Instruments []string `json:"instruments,omitempty"`
}
