// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InvestigationStatusEnum - Investigation status, either `OPEN` or `ClOSED`
type InvestigationStatusEnum string

const (
	InvestigationStatusEnumOpen   InvestigationStatusEnum = "OPEN"
	InvestigationStatusEnumClosed InvestigationStatusEnum = "CLOSED"
)

func (e InvestigationStatusEnum) ToPointer() *InvestigationStatusEnum {
	return &e
}

func (e *InvestigationStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OPEN":
		fallthrough
	case "CLOSED":
		*e = InvestigationStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InvestigationStatusEnum: %v", v)
	}
}
