// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InvestigationStatus - Investigation status, either `OPEN` or `ClOSED`
type InvestigationStatus string

const (
	InvestigationStatusOpen   InvestigationStatus = "OPEN"
	InvestigationStatusClosed InvestigationStatus = "CLOSED"
)

func (e InvestigationStatus) ToPointer() *InvestigationStatus {
	return &e
}

func (e *InvestigationStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OPEN":
		fallthrough
	case "CLOSED":
		*e = InvestigationStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InvestigationStatus: %v", v)
	}
}
