// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListDateRequest struct {
	// Associated alert ID filter
	AlertID *int64 `json:"alert_id,omitempty"`
	// Associated case ID filter
	CaseID *int64 `json:"case_id,omitempty"`
	// End date
	EndDate *string `json:"end_date,omitempty"`
	// Number of objects per page.
	Limit *int64 `json:"limit,omitempty"`
	// Pagination offset. A value of 1 returns a response beginning with the first record. The offset is relative to the number of pages (not the total count of objects)
	Offset *int64 `json:"offset,omitempty"`
	// Start date
	StartDate *string `json:"start_date,omitempty"`
}
