// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListResponse - OK
type ListResponse struct {
	// Number of objects in the response
	ResponseCount *int64 `json:"response_count,omitempty"`
	// Total number of objects in the platform.
	TotalCount *int64 `json:"total_count,omitempty"`
}
