// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MessageResponse - OK
type MessageResponse struct {
	// Detailed message
	Message *string `json:"message,omitempty"`
}
