// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Options struct {
	// Only relevant for updates/upserts, ignored otherwise. See [custom data merge strategy](doc:how-data-merges-on-updates#custom-data-merge-strategy) for more details. **Default**: `false`
	MergeCustomData *bool `json:"merge_custom_data,omitempty"`
	// If `false`, does not resolve the geographic location from the provided IP. If `true` and `digital_data.ip_addresses` is empty, Unit21 ignores the field. **Default**: `true`
	ResolveGeoip *bool `json:"resolve_geoip,omitempty"`
	// If POST request includes an object that already exists when  `upsert_on_conflict` is `false`, API returns a 409 error code and the object is not overwritten. **Default**: `true`
	UpsertOnConflict *bool `json:"upsert_on_conflict,omitempty"`
}
