// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RelationshipsDataProperties - An entity's associated intruments and entities (also called relationships)
type RelationshipsDataProperties struct {
	// List of children entities.
	Children []RelatedEntity `json:"children,omitempty"`
	// List of associated instruments.
	Instruments []RelatedInstrument `json:"instruments,omitempty"`
	// List of parent entities.
	Parents []RelatedEntity `json:"parents,omitempty"`
	// List of undirected entities.
	Undirected []RelatedEntity `json:"undirected,omitempty"`
}
