// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RelatedInstrument - Top-level data about an instrument relationship.
type RelatedInstrument struct {
	// Unique identifier of the instrument. Intrument IDs must be unique and only comprise of the characters -_:.@a-zA-Z0-9!#$%&*+/=?^`{'
	InstrumentID *string `json:"instrument_id,omitempty"`
	// Description of the relationship.
	RelationshipID *string `json:"relationship_id,omitempty"`
}
