// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RiskScoresProperties - Third party risk score information
type RiskScoresProperties struct {
	// Number by which `score`can be divided. If no value is given, Unit21 sets the denominator as 10^n, where `n`is the number of characters in the value. E.G. a value of 50 has a denominator of 10², a value of 501 has a denominator of 10³.
	//
	Denominator *int64 `json:"denominator,omitempty"`
	// Name of risk score
	Name string `json:"name"`
	// Risk Value assigned to entity
	Score int64 `json:"score"`
}
