// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SourceArray string

const (
	SourceArrayInternal SourceArray = "INTERNAL"
	SourceArrayExternal SourceArray = "EXTERNAL"
)

func (e SourceArray) ToPointer() *SourceArray {
	return &e
}

func (e *SourceArray) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "INTERNAL":
		fallthrough
	case "EXTERNAL":
		*e = SourceArray(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceArray: %v", v)
	}
}
