// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserData - Personal data - name, birthday, SSN etc.
type UserData struct {
	// Personal data - name, birthday, SSN etc. None of the fields in user_data are required. You may send in an empty array: `"user_data": {}`.
	//
	UserData *UserDataProperties `json:"user_data,omitempty"`
}
