// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"unit21/pkg/models/shared"
)

// CreateEntityMessageGeneralResponse - OK
type CreateEntityMessageGeneralResponse struct {
	// Error message
	ErrorCode *string `json:"error_code,omitempty"`
	// Detailed message
	Message *string `json:"message,omitempty"`
}

type CreateEntityResponse struct {
	ContentType string
	// OK
	MessageGeneralResponse *CreateEntityMessageGeneralResponse
	StatusCode             int
	RawResponse            *http.Response
	// OK
	CreateEntityResponse *shared.CreateEntityResponse
}
