// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DatafileStatusRequest struct {
	// Unique identifier of the datafile in the Unit21 system
	FileID int64 `pathParam:"style=simple,explode=false,name=file_id"`
}

type DatafileStatusResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
