// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeactivateAgentRequest struct {
	// Email of an agent in your organization
	AgentEmail string `pathParam:"style=simple,explode=false,name=agent_email"`
}

type DeactivateAgentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	DeactivateAgent200ApplicationJSONAny interface{}
}
