// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"unit21/pkg/models/shared"
)

type DelMediaEntityRequest struct {
	EntityID string `pathParam:"style=simple,explode=false,name=entity_id"`
	// Name of organization in your environment
	OrgName string `pathParam:"style=simple,explode=false,name=org_name"`
}

type DelMediaEntityResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// NOT FOUND
	ErrorResponse *shared.ErrorResponse
}
