// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// ExportDevicesRequestBodyFilters - Filter to narrow down devices in export
type ExportDevicesRequestBodyFilters struct {
	// Devices that belong to this Child org (Numerical ID).
	ChildOrgIds []int64 `json:"child_org_ids,omitempty"`
}

type ExportDevicesRequestBody struct {
	// Email of an agent in your organization
	AgentEmail *string `json:"agent_email,omitempty"`
	// Numerical identifier of an agent in your organization
	AgentID *string `json:"agent_id,omitempty"`
	// Array of the unique identifiers of the device IDs.
	DeviceIds []int64 `json:"device_ids,omitempty"`
	// Filter to narrow down devices in export
	Filters *ExportDevicesRequestBodyFilters `json:"filters,omitempty"`
}

type ExportDevicesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
