// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetDeviceByExternalRequest struct {
	// Identifier of the device within your system
	DeviceID string `pathParam:"style=simple,explode=false,name=device_id"`
	// Name of organization in your environment
	OrgName string `pathParam:"style=simple,explode=false,name=org_name"`
}

type GetDeviceByExternalResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
