// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetEventRequest struct {
	// Unique identifier of the event on your platform
	EventID string `pathParam:"style=simple,explode=false,name=event_id"`
	// Name of organization in your environment
	OrgName string `pathParam:"style=simple,explode=false,name=org_name"`
}

// GetEvent200ApplicationJSON - OK
type GetEvent200ApplicationJSON struct {
	// `true` if the event has been migrated to coldstore
	//
	IsColdStore *bool `json:"is_cold_store,omitempty"`
}

type GetEventResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetEvent200ApplicationJSONObject *GetEvent200ApplicationJSON
}
