// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"unit21/pkg/models/shared"
)

type GetInstrumentRequest struct {
	// Unique identifier of the instrument on your platform
	InstrumentID string `pathParam:"style=simple,explode=false,name=instrument_id"`
	// Name of organization in your environment
	OrgName string `pathParam:"style=simple,explode=false,name=org_name"`
}

// GetInstrumentMessageGeneralResponse - OK
type GetInstrumentMessageGeneralResponse struct {
	// Error message
	ErrorCode *string `json:"error_code,omitempty"`
	// Detailed message
	Message *string `json:"message,omitempty"`
}

type GetInstrumentResponse struct {
	ContentType string
	// OK
	MessageGeneralResponse *GetInstrumentMessageGeneralResponse
	StatusCode             int
	RawResponse            *http.Response
	// OK
	InstrumentList *shared.InstrumentList
}
