// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetVerificationResultRequest struct {
	// A Unit21 internally-assigned unique identifier for the verification workflow of the entity.
	ResultID string `pathParam:"style=simple,explode=false,name=result_id"`
}

type GetVerificationResultResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
