// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"bytes"
	"encoding/json"
	"errors"
	"net/http"
	"unit21/pkg/models/shared"
)

type LinkMediaToAlertRequestBodyType string

const (
	LinkMediaToAlertRequestBodyTypeArrayOflinkMediaJSON LinkMediaToAlertRequestBodyType = "arrayOflinkMediaJSON"
	LinkMediaToAlertRequestBodyTypeLinkMediaForm        LinkMediaToAlertRequestBodyType = "linkMediaForm"
)

type LinkMediaToAlertRequestBody struct {
	ArrayOflinkMediaJSON []shared.LinkMediaJSON
	LinkMediaForm        *shared.LinkMediaForm

	Type LinkMediaToAlertRequestBodyType
}

func CreateLinkMediaToAlertRequestBodyArrayOflinkMediaJSON(arrayOflinkMediaJSON []shared.LinkMediaJSON) LinkMediaToAlertRequestBody {
	typ := LinkMediaToAlertRequestBodyTypeArrayOflinkMediaJSON

	return LinkMediaToAlertRequestBody{
		ArrayOflinkMediaJSON: arrayOflinkMediaJSON,
		Type:                 typ,
	}
}

func CreateLinkMediaToAlertRequestBodyLinkMediaForm(linkMediaForm shared.LinkMediaForm) LinkMediaToAlertRequestBody {
	typ := LinkMediaToAlertRequestBodyTypeLinkMediaForm

	return LinkMediaToAlertRequestBody{
		LinkMediaForm: &linkMediaForm,
		Type:          typ,
	}
}

func (u *LinkMediaToAlertRequestBody) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	arrayOflinkMediaJSON := []shared.LinkMediaJSON{}
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&arrayOflinkMediaJSON); err == nil {
		u.ArrayOflinkMediaJSON = arrayOflinkMediaJSON
		u.Type = LinkMediaToAlertRequestBodyTypeArrayOflinkMediaJSON
		return nil
	}

	linkMediaForm := new(shared.LinkMediaForm)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&linkMediaForm); err == nil {
		u.LinkMediaForm = linkMediaForm
		u.Type = LinkMediaToAlertRequestBodyTypeLinkMediaForm
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u LinkMediaToAlertRequestBody) MarshalJSON() ([]byte, error) {
	if u.ArrayOflinkMediaJSON != nil {
		return json.Marshal(u.ArrayOflinkMediaJSON)
	}

	if u.LinkMediaForm != nil {
		return json.Marshal(u.LinkMediaForm)
	}

	return nil, nil
}

type LinkMediaToAlertRequest struct {
	RequestBody *LinkMediaToAlertRequestBody `request:"mediaType=application/json"`
	// A Unit21 internally-assigned unique identifier for an object within the Unit21 system. Depending on the endpoint, `unit21_id` can refer to an entity, an event, a case, an alert, a device, etc.
	Unit21ID string `pathParam:"style=simple,explode=false,name=unit21_id"`
}

type LinkMediaToAlertResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
