// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"bytes"
	"encoding/json"
	"errors"
	"net/http"
	"unit21/pkg/models/shared"
)

type LinkMediaToCaseRequestBodyType string

const (
	LinkMediaToCaseRequestBodyTypeArrayOflinkMediaJSON LinkMediaToCaseRequestBodyType = "arrayOflinkMediaJSON"
	LinkMediaToCaseRequestBodyTypeLinkMediaForm        LinkMediaToCaseRequestBodyType = "linkMediaForm"
)

type LinkMediaToCaseRequestBody struct {
	ArrayOflinkMediaJSON []shared.LinkMediaJSON
	LinkMediaForm        *shared.LinkMediaForm

	Type LinkMediaToCaseRequestBodyType
}

func CreateLinkMediaToCaseRequestBodyArrayOflinkMediaJSON(arrayOflinkMediaJSON []shared.LinkMediaJSON) LinkMediaToCaseRequestBody {
	typ := LinkMediaToCaseRequestBodyTypeArrayOflinkMediaJSON

	return LinkMediaToCaseRequestBody{
		ArrayOflinkMediaJSON: arrayOflinkMediaJSON,
		Type:                 typ,
	}
}

func CreateLinkMediaToCaseRequestBodyLinkMediaForm(linkMediaForm shared.LinkMediaForm) LinkMediaToCaseRequestBody {
	typ := LinkMediaToCaseRequestBodyTypeLinkMediaForm

	return LinkMediaToCaseRequestBody{
		LinkMediaForm: &linkMediaForm,
		Type:          typ,
	}
}

func (u *LinkMediaToCaseRequestBody) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	arrayOflinkMediaJSON := []shared.LinkMediaJSON{}
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&arrayOflinkMediaJSON); err == nil {
		u.ArrayOflinkMediaJSON = arrayOflinkMediaJSON
		u.Type = LinkMediaToCaseRequestBodyTypeArrayOflinkMediaJSON
		return nil
	}

	linkMediaForm := new(shared.LinkMediaForm)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&linkMediaForm); err == nil {
		u.LinkMediaForm = linkMediaForm
		u.Type = LinkMediaToCaseRequestBodyTypeLinkMediaForm
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u LinkMediaToCaseRequestBody) MarshalJSON() ([]byte, error) {
	if u.ArrayOflinkMediaJSON != nil {
		return json.Marshal(u.ArrayOflinkMediaJSON)
	}

	if u.LinkMediaForm != nil {
		return json.Marshal(u.LinkMediaForm)
	}

	return nil, nil
}

type LinkMediaToCaseRequest struct {
	RequestBody *LinkMediaToCaseRequestBody `request:"mediaType=application/json"`
	// A Unit21 internally-assigned unique identifier for an object within the Unit21 system. Depending on the endpoint, `unit21_id` can refer to an entity, an event, a case, an alert, a device, etc.
	Unit21ID string `pathParam:"style=simple,explode=false,name=unit21_id"`
}

type LinkMediaToCaseResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	LinkMediaToCase200ApplicationJSONAny interface{}
}
