// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BlacklistINET struct {
	// Either IPv4 or IPv6
	IPAddress string `json:"ip_address"`
	// Origin of IP
	Source *string `json:"source,omitempty"`
}
