// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BulkExportResponse - OK
type BulkExportResponse struct {
	// Export success.
	Message *string `json:"message,omitempty"`
}
