// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BusinessDataProperties - Business data - business name, TIN/EIN etc. None of the fields in business_data are required. You may send in an empty array: `"business_data": {}`.
type BusinessDataProperties struct {
	// The name of the main person associated with the business
	AccountHolderName *string `json:"account_holder_name,omitempty"`
	// The registered name of the business
	BusinessName *string `json:"business_name,omitempty"`
	// The TIN/EIN of the business
	CorporateTaxID *string `json:"corporate_tax_id,omitempty"`
	// Operating name of the business.
	DoingBusinessAs *string `json:"doing_business_as,omitempty"`
	// Country where the business is registered. Provided acording to the ISO 3166-1 alpha-2 standard.
	RegisteredCountry *string `json:"registered_country,omitempty"`
	// Any string representing a state such as "CA" or "California"
	RegisteredState *string `json:"registered_state,omitempty"`
	// The website or associated URL for the business
	Website *string `json:"website,omitempty"`
}
