// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CommunicationDataProperties - An entity's associated means of communication, like emails and phone numbers.
type CommunicationDataProperties struct {
	// List of emails associated with an entity.
	EmailAddresses []string `json:"email_addresses,omitempty"`
	// List of phone numbers associated with the entity in [E.164 format](https://en.wikipedia.org/wiki/E.164)─e.g. +12125551395 ( '[+][country code][area code][local phone number]' )
	PhoneNumbers []string `json:"phone_numbers,omitempty"`
}
