// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateDeviceResponse - OK
type CreateDeviceResponse struct {
	// Identifier of the device within your system
	DeviceID *string `json:"device_id,omitempty"`
	// OPTIONAL. During upserts, `true` if all fields are identical to already existing fields for that object
	Ignored *bool `json:"ignored,omitempty"`
	// During upserts, `true` when object already existed at the ID field specified in the POST.
	PreviouslyExisted *bool `json:"previously_existed,omitempty"`
	// A Unit21 internally-assigned unique identifier for an object within the Unit21 system.
	Unit21ID *string `json:"unit21_id,omitempty"`
}
