// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Devices - Top-level data about an instrument.
type Devices struct {
	// Application version used by the device
	AppVersion *string `json:"app_version,omitempty"`
	// Identifier of the device within your system
	DeviceID string `json:"device_id"`
	// Manufacturer of the device value
	DeviceManufacturer *string `json:"device_manufacturer,omitempty"`
	// Specific device model number value
	DeviceModel *string `json:"device_model,omitempty"`
	// SubType of device
	DeviceSubtype *string `json:"device_subtype,omitempty"`
	// Type of device
	DeviceType string `json:"device_type"`
	// Network carrier used by the device (T-Mobile, Verizon etc.)
	NetworkCarrier *string `json:"network_carrier,omitempty"`
	// Whether or not the device has a cellular connection
	NetworkCellular *bool    `json:"network_cellular,omitempty"`
	Options         *Options `json:"options,omitempty"`
	// Operating system used by the device
	OsName *string `json:"os_name,omitempty"`
	// Operating system version used by the device
	OsVersion *string `json:"os_version,omitempty"`
	// List of phone numbers associated with the entity in [E.164 format](https://en.wikipedia.org/wiki/E.164)─e.g. +12125551395 ( '[+][country code][area code][local phone number]' )
	PhoneNumbers []string `json:"phone_numbers,omitempty"`
	// Date in seconds since 1 Jan 1970 00:00:00 UTC (i.e. in [Unix time](https://en.wikipedia.org/wiki/Unix_time)).
	RegisteredAt *int64 `json:"registered_at,omitempty"`
	// Status of the object on your system. You MAY enter any string value.
	Status *string `json:"status,omitempty"`
	// List of string tags, in the format `keyString:valueString` (note that the Key strings are NOT enclosed in `"`)
	Tags []string `json:"tags,omitempty"`
	// Timezone configured by the device's application/OS
	Timezone *string `json:"timezone,omitempty"`
}
