// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DocumentDataProperties - document data properties
type DocumentDataProperties struct {
	// provided acording to the [ISO 3166-1 alpha-2 standard](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2].
	Country *string `json:"country,omitempty"`
	// The id or number of the document
	DocumentID string `json:"document_id"`
	// The type of the document (i.e. drivers license)
	DocumentType string `json:"document_type"`
	// Date when document expires, in seconds since 1 Jan 1970 00:00:00 UTC (i.e. in [Unix time](https://en.wikipedia.org/wiki/Unix_time))".
	ExpiresAt *int64 `json:"expires_at,omitempty"`
	// Date when document was created, in seconds since 1 Jan 1970 00:00:00 UTC (i.e. in [Unix time](https://en.wikipedia.org/wiki/Unix_time))".
	IssuedAt *int64 `json:"issued_at,omitempty"`
	// Any string representing a state such as "CA" or "California"
	State *string `json:"state,omitempty"`
	// Date when document was verified, in seconds since 1 Jan 1970 00:00:00 UTC (i.e. in [Unix time](https://en.wikipedia.org/wiki/Unix_time))".
	VerifiedOn *int64 `json:"verified_on,omitempty"`
}
