// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EntityOptions struct {
	// Options for specifying workflows and list merge strategies.
	Options *EntityOptionsProperties `json:"options,omitempty"`
}
