// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EntityOptionsPropertiesIdentityVerifications struct {
	// Include the full, raw, verification results. Can be used only if `synchronous_response` is `true`. Default is `false`.
	IncludeFullResponse *bool `json:"include_full_response,omitempty"`
	// Whether or not to execute a verification workflow for the uploaded entity/entities. **Default**: `false`
	RunVerifications *bool `json:"run_verifications,omitempty"`
	// Socure API Key
	SocureOverrideAPIKey *string `json:"socure_override_api_key,omitempty"`
	// **Default**: `false`. If `true`,  the APU immediately executes the workflow, and sends the verification result with the API response. If `true` and the workflow doesn't allow synchronous responses, the API returns an error.
	// **Note**: Using synchronous calls may cause the API to return a `423` error. If that happens, try switching `synchronous_response` to `false`.
	SynchronousResponse *bool `json:"synchronous_response,omitempty"`
	// A unique identifier defined during workflow creation. **Default**: none
	//
	WorkflowID *string `json:"workflow_id,omitempty"`
}

// EntityOptionsProperties - Options for specifying workflows and list merge strategies.
type EntityOptionsProperties struct {
	IdentityVerifications *EntityOptionsPropertiesIdentityVerifications `json:"identity_verifications,omitempty"`
	// Only relevant for updates/upserts, ignored otherwise. See [custom data merge strategy](doc:how-data-merges-on-updates#custom-data-merge-strategy) for more details. **Default**: `false`
	MergeCustomData *bool `json:"merge_custom_data,omitempty"`
	// If `false`, does not resolve the geographic location from the provided IP. If `true` and `digital_data.ip_addresses` is empty, Unit21 ignores the field. **Default**: `true`
	ResolveGeoip *bool `json:"resolve_geoip,omitempty"`
	// If POST request includes an object that already exists when  `upsert_on_conflict` is `false`, API returns a 409 error code and the object is not overwritten. **Default**: `true`
	UpsertOnConflict *bool `json:"upsert_on_conflict,omitempty"`
}
