// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ErrorResponse - NOT FOUND
type ErrorResponse struct {
	// Error message
	ErrorCode *string `json:"error_code,omitempty"`
}
