// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GeneralEntitiesBasic struct {
	// General information about the entity. With this object, you can link any entity on Unit21's system to a user or business on your platform.
	GeneralData *GeneralEntitiesPropertiesBasic `json:"general_data,omitempty"`
}
