// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GeneralEntitiesPropertiesParents struct {
	// Parent unique identifier
	EntityID *string `json:"entity_id,omitempty"`
	// Describes a user such as `employee` or `business`
	EntityType *string `json:"entity_type,omitempty"`
}

// GeneralEntitiesProperties - General information about the entity. With this object, you can link any entity on Unit21's system to a user or business on your platform.
type GeneralEntitiesProperties struct {
	// Unique identifier of the entity. Entity IDs must be unique and only comprise of the characters -_:.@a-zA-Z0-9!#$%&*+/=?^`{'
	EntityID string `json:"entity_id"`
	// Extra information how your organization classifies the entity. You MAY enter any value.
	//
	EntitySubtype *string `json:"entity_subtype,omitempty"`
	// Describes a user such as `employee` or `business`
	EntityType *string `json:"entity_type,omitempty"`
	// The parent object consists of two fields─`entity_id` for parent unique identifier  and `entity_type`.
	Parents []GeneralEntitiesPropertiesParents `json:"parents,omitempty"`
	// Date in seconds since 1 Jan 1970 00:00:00 UTC (i.e. in [Unix time](https://en.wikipedia.org/wiki/Unix_time)).
	RegisteredAt *int64 `json:"registered_at,omitempty"`
	// Status of the object on your system. You MAY enter any string value.
	Status *string `json:"status,omitempty"`
	// List of string tags, in the format `keyString:valueString` (note that the Key strings are NOT enclosed in `"`)
	Tags []string `json:"tags,omitempty"`
}
