// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// InvestigationStatusEnum - Investigation status, either `OPEN` or `ClOSED`
type InvestigationStatusEnum string

const (
	InvestigationStatusEnumOpen   InvestigationStatusEnum = "OPEN"
	InvestigationStatusEnumClosed InvestigationStatusEnum = "CLOSED"
)

func (e *InvestigationStatusEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "OPEN":
		fallthrough
	case "CLOSED":
		*e = InvestigationStatusEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for InvestigationStatusEnum: %s", s)
	}
}
