// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LinkMediaJSON struct {
	// Any custom information that you want the Unit21 system to associate with this object (accepts any valid JSON object)
	CustomData map[string]interface{} `json:"custom_data,omitempty"`
	// Base64 encoded media file
	Media *string `json:"media,omitempty"`
	// Type of media. The dropdown contains Unit21-recognized types.
	//
	// Though you can provide any string, Unit21 processes and display recognized `media_type` values with custom formatting. Unit21 can also use recognized media object types for dedicated requests, like document verification.
	//
	MediaType *MediaTypeEnum `json:"media_type,omitempty"`
	// name of media object
	Name *string `json:"name,omitempty"`
}
