// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// LinkInstrument - Associate an instrument directly with an object, like an Entity or Case.
type LinkInstrument struct {
	// an array of instruments specified by their `instrument_id`. See [instruments](https://guide.unit21.ai/reference#instruments-1) section to update.
	InstrumentIds []string `json:"instrument_ids,omitempty"`
}
