// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListRequest struct {
	// Number of objects per page.
	Limit *int64 `json:"limit,omitempty"`
	// Pagination offset. A value of 1 returns a response beginning with the first record. The offset is relative to the number of pages (not the total count of objects)
	Offset *int64 `json:"offset,omitempty"`
}
