// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListExports struct {
	// IDs for the files to export
	FileExportIds []int64 `json:"file_export_ids,omitempty"`
	// Number of objects per page.
	Limit *int64 `json:"limit,omitempty"`
	// Pagination offset. A value of 1 returns a response beginning with the first record. The offset is relative to the number of pages (not the total count of objects)
	Offset *int64 `json:"offset,omitempty"`
	// Statuses for the files to export. One of READY_FOR_DOWNLOAD, GENERATING, FAILED, REQUESTED
	Statuses []string `json:"statuses,omitempty"`
}
