// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListAlertRequest struct {
	// Associated alert ID filter
	AlertID *int64 `json:"alert_id,omitempty"`
	// Number of objects per page.
	Limit int64 `json:"limit"`
	// Pagination offset. A value of 1 returns a response beginning with the first record. The offset is relative to the number of pages (not the total count of objects)
	Offset int64 `json:"offset"`
}
