// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LocationDataArray struct {
	// Array of location data objects.
	LocationData []LocationDataProperties `json:"location_data,omitempty"`
}
