// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RelationshipsData struct {
	// An entity's associated intruments and entities (also called relationships)
	Relationships *RelationshipsDataProperties `json:"relationships,omitempty"`
}
