// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RiskScores struct {
	// Set of `risk scores`
	RiskScores []RiskScoresProperties `json:"risk_scores,omitempty"`
}
